### ISSUE TITLE
Lyn: Final Smash

### ISSUE THREAD

**Issue by MrGameCrazy** [TheOriginalSINe/Project-M-CC#138]
Atm, Lyn's final smash is currently Pit's final smash. Will it be possible to change Lyn's final smash to her critical hit move?

This is a video I found of Lyn's critical hit in the Fire Emblem GBA game. https://www.youtube.com/watch?v=GYYW9KxHkrw

**Comment by jojmaht** [comment]
I think we could maybe salvage parts of Meta-Knight's final Smash to do this.

**Comment by JackpotSHUnited** [comment]
Some of the graphics from her Assist Trophy could be used as well.

**Comment by ghost** [comment]
Someone on the Discord chat for Lyn mentioned that there was a way to bring over Marth's FS stuff as a base.

**Comment by MrGameCrazy** [comment]
That's good to hear.

**Comment by SzionBlue** [comment]
Best of luck!! =)

**Comment by ghost** [comment]
We have a text file of the PSA data for this, but it needs to be implemented by someone who is knowledgeable about PSA(the program).

**Comment by TheSmashBoy** [comment]
Is anyone currently working on her Final Smash?

**Comment by MrGameCrazy** [comment]
I have no idea tbh.

**Comment by TheSmashBoy** [comment]
@MrGameCrazy I recently got informed a few events in the Matrix at Vector and on reddit. They are actually still working on them. bb010g is specifically trying to figure out how PMEX works so that he can import CC characters into their Ex version without tampering their animations and cosmetic data. It's a lot of work.
