### ISSUE TITLE
Isaac: Stock Icons

### ISSUE THREAD

**Issue by ewmb7701** [TheOriginalSINe/Project-M-CC#14]
Isaac does not use his stock icons present in the info files

Suggested Fix:
Redirect Isaac to use these stock icons. (Don't know/remember how to do this at the moment, research needs to be done)

**Comment by bb010g** [comment]
Can we label these with character names?

**Comment by jgd124** [comment]
I'm not sure if this is _the_ fix you all are looking for, but a modder named likiji123 has created _a_ fix and several custom icons for Knuckles, Lyn, and Isaac in this thread --> http://smashboards.com/threads/knuckles-lyn-and-isaac-stock-icons.425088/

Not sure how supportive he would be to be included in this project, but maybe there's a way to figure out how he did it via the files provided.

**Comment by Nekudot** [comment]
Here's a fix for Isaac stocks, the default stock now has a black outline and was recolored for all the costumes, they all work in-game and on the results screen. Unfortunately I can't make a fork, so someone else needs to do a pull request. I downloaded the latest files as of now and edited them, so they need to be uploaded before the base files get updated to avoid problems.
_outdated link removed_

Info.pac goes in /projectm/pf/info2/
StockFaceTex.brres goes in /projectm/pf/menu/common/
sc_selcharacter.pac in /projectm/pf/menu2/
STGRESULT.pac in /projectm/pf/stage/melee/

Edit: Link removed because the base files got changed, tell me again when they're needed, or I'll submit a pull request ...someday
