### ISSUE TITLE
Lyn: Spot Dodge Normalization

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#155]
Lyn has most of the stats of the low tier spot dodge (invulnerability starts on frame 2, lasts until frame 15) but her first actionable frame is 22. When all spot dodges were normalize in 3.6, characters with this spot dodge were all given a first actionable frame of 25.

Suggested fix: Make Lyn's First Actionable Frame out of spot dodge 3 frames later.

**Comment by somealternateaccount** [comment]
Maybe this issue can be resolved along with #106, if we can get an animator to create a slightly slower animation that does not cause her to stab herself.

**Comment by somealternateaccount** [comment]
Needs discussion on Lyn's spot dodge speed - should it be intangible on [2, 15] and FAF on 25, or be intangible on [2, 18] and FAF on 28? I'm partial to the former speed, since Lyn is supposed to be an "even faster" sword user, but others have brought up that all other Fire Emblem characters have the 28-frame spot dodge.

**Comment by ArtfulHobbes** [comment]
For consistency sake, I'm going to vote for 28 FAF spotdodge.

**Comment by somealternateaccount** [comment]
+1 on 25 FAF

**Comment by AgentBlizz** [comment]
I'd be happy with the 28 FAF

**Comment by JCOnyx** [comment]
I'm good with either tbh, but going from the first post in this issue, 25 seems like what we should aim for and matches her speedier character type better.

**Comment by ghost** [comment]
My vote is for 25.

EDIT: Meant 25. She had the same spot dodge length as other characters with an FAF of 25, but her FAF came out 3 frames early. Minimal change would just be to fix the FAF.

**Comment by vinegar97** [comment]
Is there a reason for FE character to actualy have the different FAF frames ?, i say that might help us in deciding.

**Comment by JackpotSHUnited** [comment]
What's Pit's FAF frame count? Since she was originally cloned from him, after all.

**Comment by ArtfulHobbes** [comment]
Pit's is 25

**Comment by ghost** [comment]
Who the clone is based on shouldn't influence their stats. They are completely different characters that play differently.

If I'm not mistaken Mewtwo was a Lucario clone, and their playstyles couldn't be more different.

**Comment by Grangach** [comment]
I don't think we should tie lyn down to what the other sword users do. If 25 faf fits her core design better we should go with that, it may also be that having a faf of 22 is an intentional quirk that benefits her core design. She's got fast strong but punishable attacks right? So maybe being able to threaten with a fast spot dodge is important for her.

**Comment by ghost** [comment]
@Grangach in 3.6 every single character was normalize to three types of spot dodges, with first actionable frames of 25, 28, and 31. Leak Lyn has all the properties of the 25 FAF one but her FAF is 3 frames early.

**Comment by Grangach** [comment]
Oh ok, then yes I would vote for 25, seems more in line with her design.

**Comment by vinegar97** [comment]
I vote for 25 too. For the same a reason as the above

**Comment by bb010g** [comment]
Closed in #275.
