### ISSUE TITLE
Commits to master without issues, no changelogs.

### ISSUE THREAD

**Issue by somealternateaccount** [TheOriginalSINe/Project-M-CC#187]
People are submitting pull requests without useful descriptions, or committing directly to master (!) without descriptions on their commits. It will be incredibly difficult to build a changelog.

The lackadaisical approach to source control has already resulted in a CSS with Ridley on it being committed to master, and now I think all of the CSS icons are different? The stage select screen images are incredibly fuzzy... it looks like somebody's bad personal build if changes like these get into master.

People need to be more rigorous about their changes, avoid committing directly to master, and open issues or pull requests for _every change_ while including full changelogs. A lot of commits need to be looked at to verify what should have changed and what should not have changed.

**Comment by somealternateaccount** [comment]
@TheOriginalSINe @Azuran01 @Rage17 @skinnyfoetusboy @bb010g @JCOnyx

**Comment by ghost** [comment]
As I've been saying, there should be no commits to master for any changes not covered by an issue. Every potential change should be listed on git so discussion can be had and tracked before anything is implemented.

Additionally, the number of listed contributors should be kept to a minimum and include only people who adhere to the proper process and have a good understanding of the project goals.

**Comment by Nekudot** [comment]
This is why I find all the move and balance changes that get pushed to master bad, because there was no Pull Request with the specific changes done with references to the issues they are trying to fix. Only two or three people saw them and then it was decided to upload it directly? Isn't that too hasty?

**Comment by somealternateaccount** [comment]
I'd like if we could move to an RFC system, where prior to making balance changes to the new characters an RFC is opened as an issue so that the changes may be discussed.

edit:  
So the workflow for changes or improvements would be, on an example of a character's move balance:
1. RFC is opened to discuss character balance on a move.
2. Discussion takes place regarding how the move is balanced or imbalanced, and changes are decided on.
3. The changes are made on a fork and tested.
4. If the changes are good, a pull request is made with a detailed description of the changes and tagged on the issue to invite more discussion on the final changes.
5. If the pull request and RFC are good, the pull request is merged to `master`.

And the workflow for bugs (specifically: things that do not work as intended, cause crashes, etc. This is not the place for e.g. SSS changes) would be:
1. Issue is opened regarding a bug.
2. Discussion takes place on how to fix the bug.
3. The changes are made on a fork and tested.
4. If the changes are good, a pull request is made with a detailed description of the changes and tagged on the issue to make it more obvious what the pull request is addressing.
5. If the pull request is good, the pull request is merged to `master`.

edit 2:  
And, of course, pull requests with little to no descriptions of their changes would be rejected even if they were the solution to an issue. We need descriptions of changes so we can build a proper changelog.

**Comment by ghost** [comment]
@Nekudot do you know specific balance changes that were made without an issue or commit comment? We should try to revert any undocumented changes.

**Comment by UltraSyko** [comment]
"The stage select screen images are incredibly fuzzy... it looks like somebody's bad personal build if changes like these get into master."

I was really disappointed when the Stage Select Screen was overwritten because now all my HD Textures (Dolphin Load) won't appear anymore. I could take the time to redo every single portrait, but I'm afraid it's gonna happen again in future updates. So I don't wanna waste my time editing it just for my own personal needs...It's a shame I have to see compressed 480p pictures ;c

**Comment by Nekudot** [comment]
@Azuran01 Not really, I haven't downloaded the entire build in a few days. I wouldn't be surprised if they exist though. I'm mainly talking about stuff like Lyn's unnecesary BAir nerf that happened a few days ago. That eventually got fixed, but it could have been avoided if a Pull Request or something was made before submiting the files and people could test them, instead of creating new issues when trying to "solve" previous ones. Commits like that should only be made when the changes needed are absolute and not subjetive.
Edit: basically what @somealternateaccount said
On a semi unrelated note, I'm still not completely on board with the broken and unfinished 64 mode being included, but invisible brawl is a mode no one plays anyway

**Comment by bb010g** [comment]
I'd be on board with moving to what Dolphin does. Make every commit go through a pull request and be signed off by at least one other person.

**Comment by ghost** [comment]
@bb010g that may be a good idea.

@Nekudot the "KBG nerf" on Lyn's bair was less of an undocumented change and more of an oversight. KBG values were never touched, but a move's damage influence it's KB. So when we nerfed damage we just forgot to adjust KBG to compensate.

**Comment by bb010g** [comment]
[Git Town](http://www.git-town.com/) is a very nice piece of tooling for a forking workflow.

**Comment by somealternateaccount** [comment]
@bb010g +1 for pull requests with sign-offs.

**Comment by jojmaht** [comment]
I would be in favor of a minimum of three contributors signing on a PR.
I would also like each commit to include a full file-by-file changelog,
maybe even with screenshots.

**Comment by Kippy232** [comment]
For the sake of clarity, which branch should be downloaded, be it for testing purposes, or simply to keep up to date with changes?

**Comment by somealternateaccount** [comment]
@Kippy232 `master`, in the future please ask questions like this on the Discord chat.
@Azuran01 You still haven't cleaned up your `commit1` branch.

**Comment by ewmb7701** [comment]
Sorry I've been away for a few days, I had some stuff going on. I removed collaborators for now, so all pull requests have to be approved by me for now. 

You guys ABSOLUTELY have to put in change logs for your commits. I can't seem to find where exactly when the map screen changed to have these issues, as there's no changelogs for this thing. I will have to revert it back a few commits.

We need some kind of quality control system in the future. Changelogs are a good start, but I agree with the signing off thing. Screenshots should be encouraged but optional.

EDIT: 
I posted this in the Discord chat, but I want this to be better documented:

If you are making changes, you should be the one making pull requests and commits. This is to prevent issues in finding out who did what, and to make sure changelogs are more accurate.

**Comment by somealternateaccount** [comment]
Appears that this has mostly been resolved - now that pull requests require the approval of 2/5 of the collaborators to be merged, it will be up to the collaborators to ensure that proper information is included.
