### ISSUE TITLE
Lyn sfx still works when metal box is on

### ISSUE THREAD

**Issue by cooldunin97** [TheOriginalSINe/Project-M-CC#188]

**Comment by somealternateaccount** [comment]
From discussion in Discord, it appears that Lyn's voice still works when she's turned to metal. @Rage17 appears to have a solution that may work, hopefully he will reply here.

**Comment by UltraSyko** [comment]
Project M tends to miss that a lot. That even happened with Roy and Mewtwo (though I think it's been forever fixed). This is Low Priority imo

**Comment by cooldunin97** [comment]
%100 agree @Psycho-Hedgie

**Comment by Tac24** [comment]
yes Roy and Mewtwo still have this as of 3.6

**Comment by somealternateaccount** [comment]
If this occurs with Roy and Mewtwo as well it may not be a blocker for Lyn's completion. It would be nice if this issue could be resolved for all clone engine characters, if anybody would like to take a crack at it.

**Comment by ghost** [comment]
http://www.mediafire.com/download/d8ca51peab6rq8w/FitMewtwo.pac That link has a fix for 3.6 Mewtwo. It seems like 3.61 Mewtwo has new graphics for some moves, so we may want to diff check the two files. Also, this file can get looked at for using the same fix on the other clone engine characters.

**Comment by vinegar97** [comment]
I have remade the fix with mewtwo's moveset file from this build as a base, however some sounds still play after picking up a metal box, i might have to review the file again, to make sure i haven't missed any instances of the fix.

On a slightly related note, does anybody know how to find which sound ID in the moveset file corresponds to which sound effect in the .sawnd file ? That would make my life easier if i start applying  the fix for the other characters.
