### ISSUE TITLE
N64 Mode Completion

### ISSUE THREAD

**Issue by PyotrLuzhin** [TheOriginalSINe/Project-M-CC#192]
How high of a priority is N64 Mode to this project? I've been drafting a code for it, and I'd like to know if you guys are interested. The code in question would do more than just affect the character cosmetics, however; it has the potential to modify the CSS to include only the original 12, allow the game to access new PSAs and character models matching their N64 incarnations, change game physics to more closely match those of SSB, and more. I worry, however, that this might outstrip the bounds of even what the PMDT intended to do with the mode, so I'll leave it up to you guys to decide whether it should be included in this build. I'll release it publicly regardless, so it really comes down to what you guys think the PMDT's vision was.

**Comment by jgd124** [comment]
Woah. I mean, wow. That's an /amazing/ idea. I'd personally be interested, but...

I have a suspicion that this was beyond what the PMDT intended, considering the whole "clear mode" thing.

I'd absolutely follow along, though, and I'd be all about seeing this implemented.

**Comment by ghost** [comment]
I like it sans stripping the roster down for the mode. Kind of defeats the purpose of the rest of the models, and PMDT meant for it to be with the entire roster.

**Comment by bb010g** [comment]
I can see a couple of ways N64 could go. One is Reality 64 style (@Rage17 could probably talk here), with large overhauls when activated, one is purely cosmetic (costumes, sounds), one is cosmetic and restrictive (only 12, only N64 stages). I'd go for cosmetic only, but I'm interested in seeing PM: Reality 64 Lite.

Have you figured out how to change sounds with the mode?

**Comment by ghost** [comment]
If we want to work with the Reality 64 team on the mode, I am a dev there as well. Also, changing sounds (aide from on hit ones) can be done without codes already.

**Comment by UieSolverofThings** [comment]
It was originally the plan of the PMDT to have 64 physics and SFX, they've said they wanted to go nuts with the code.

**Comment by PyotrLuzhin** [comment]
@Rage17 Yeah, I'd be interested. 

@bb010g All sounds, including menu and announcer sounds, would be modified.

**Comment by ghost** [comment]
@UieSolverofThings source?

**Comment by ghost** [comment]
@PyotrLuzhin by chance will Sami be ready this week like planned? (Don't stress over it though, heard you have finals around now)

**Comment by bb010g** [comment]
Would there be a way to separate turning on the N64 cosmetics and N64 everything? I'd like to be able to do only N64 aesthetic, but still have the option go all in.

**Comment by vinegar97** [comment]
I vote to keep the roster intact and change sfx ,models ,and physics. And if you figured out how to make characters load alternate clear mode models ,that would be super !

**Comment by ghost** [comment]
Oh yeah, Alt colors for most chars have to be loaded somehow.

**Comment by somealternateaccount** [comment]
To be clear, this would activate in place of Invisible Brawl, correct? If you could keep a list of all of your changes that would help us immensely.

Thank you so much for your hard work.

**Comment by bb010g** [comment]
@vinegar97 For future reference, commas on the other side of word boundries

**Comment by vinegar97** [comment]
@bb010g noted, man i suck at using punctuation!

**Comment by Nekudot** [comment]
This sounds really good, but is it really necessary to remove everyone who wasn't in SSB for this to work? I think the main reason behind this mode was to use the new characters in a different environment. This would be a PSA nightmare with 45 characters...

**Comment by bb010g** [comment]
Why would we have to remove characters? Also, I think we already have at least half the cast's N64 primary costume done.

**Comment by JackpotSHUnited** [comment]
Making the physics identical to Smash 64 is probably unnecessary. Even in the trailer itself was just turbo mode with N64 textures; hitstun and everything else still matched Project M.

**Comment by JCOnyx** [comment]
Well, I'd personally like to see the physics match 64 if it's at all possible. Heck, maybe even remove the characters ability to use SideB.

But I'd like to see the entire PM cast in this, not just the original 12. That seems counterproductive to us adding all these new models.

**Comment by pvrker** [comment]
I think this is a really cool idea, but what do you mean by physics changes?
I'd be down for _engine_ changes such:
- Classic Z-Cancelling (L-Cancelling puts you into standing)
- No DI, only SDI

I'm not sure about the DI but if you pay attention Z-Cancelling was in the [trailer](https://youtu.be/dOuXKCvhTvw?t=16) (look closely, not all the segments were in Turbo Mode).

I'm a bit partial to gravity changes to better match 64 as it would likely effect the comboing and setups that we already know well for all the characters. I'm also not sure about things like removing one of each characters specials. I'd rather this be Project M: Retro Mode, though I wouldn't mind seeing either of those features in Reality 64.

Otherwise, sounds like good stuff and we'd all like to see what you've got cooking.

**Comment by UieSolverofThings** [comment]
@pvrker That's exactly what it is though

Special Brawl -> Retro Mode

Gives you N64 models and Smash 64 physics and mechanics, ect.

Not something that's replacing the main game. It's completely optional like Turbo Mode

**Comment by pvrker** [comment]
Maybe I wasn't clear, all I'm saying is I feel gravity changes might make the mode feel _too_ different from the main game. Who knows though, it might work out just fine. I'm just wondering how is it going to work? Is there a global gravity variable or is fall speed character specific?

There's two reasons I don't think things like entire kits and knockback amounts & angles should be changed to their 64 versions. First, it would make characters feel unfamiliar and secondly, we have no basis for what should be done to all of the newcomers since 64. However, I do believe that movesets, kits, physics and the cast (ie. original 12) should definitely be overhauled ("reverted") to better match Smash 64 for Reality 64 (btw @Rage17 didn't know you were a part of it, or that it was still alive for that matter).

I also forgot to mention that I would definitely love to see all of the hit sounds return as well as the little sparkle when you fastfall.

**Comment by Karrotkonvoy** [comment]
I'd say in the long run just keep the cosmetics and sfx in Retro/N64 mode over invisible mode, then maybe put the physics/mechanics changes in over one of the gravity modes. Limiting the roster or moves seems like overkill, the goal should be a 64 twist on PM, not a replica of 64.

As well, in terms of getting what was leaked fully fleshed out and functional, I'd say the first milestone would be to add N64 models for the whole roster and get alts to load with every character. Then we could move on to other cosmetic alterations and think about what kind of physical or mechanical changes may or may not have been implemented.

**Comment by somealternateaccount** [comment]
Tagged additionally as user interface, as this will requiring changing the Special Brawl menu to reflect the additional mode(s).

It would be interesting if the new physics replaced a separate mode from the new models, but I'm not sure that is necessary and it might be unclear.

**Comment by pharoahfawcett** [comment]
i'd like to see the completion of N64 mode. if it could be a fork project so that more attention could be directed towards it without interfering with the other issues, that would be insane.

then when it's finished it can be officially added into the PMCC build

**Comment by ghost** [comment]
If the event that it's decided that this mode is "fully fleshed out" it could easily dwarf the amount of work for most of the rest of PMCC. So far what it sounds like is:
- Every character has a 64 model. Create and implement a code that allows for multiple fitSpy costumes so each character can also have multiple skins for their 64 model. Create all those skins.
- Create and implement a code that enables physics to be changed while in 64 mode. Create all sorts of new physics changes that stays true to 64 physics engine.
- Create and implement code that enables full lag canceling with L cancels in 64 mode. Same for removing DI.
- Import a metric shitton of new sound effects. Create and implement code that overwrites the standard sound effects when in 64 mode.

Out of all of these, the only ones that sound reasonable to me, at least for PMCC first release, would be giving everyone 64 models and maybe full lag L canceling.

A fully fleshed out version of this may be something to be considered for a later release, or maybe a separate mod project.

**Comment by jojmaht** [comment]
We could do it bit by bit. Like, having a minimally viable product would be just having all characters having their N64 model. Then we could build upon that, bringing physics, sound effects, alts, etc. over time.

**Comment by bb010g** [comment]
:+1: for gradual progress. Nobody plays Invisible Brawl, so it shouldn't be an issue to keep the work in master.

**Comment by ghost** [comment]
Then can we at least come to agree on reasonable goals to include for the first "release" build?

So far the release build is 3.61 + complete and bug fixed Lyn and Knuckles, plus the unfinished leaked alts and costumes. As I said before, I think a feasible basis for a release ready 64 mode is base models for everyone and full lag L canceling. Anything more than that seems it would take a lot more time to complete.

**Comment by bb010g** [comment]
If @PyotrLuzhin has already figured out how to activate physics codes with Retro, those should be quick. Reality 64 already has a physics code list in their main topic.

**Comment by DarkLink1996** [comment]
I can see Retro Physics/PSAs being accessed though a different setting than N64 Mode's models. Maybe a though the options menu like how Stamina's overhaul was.

**Comment by vinegar97** [comment]
@DarkLink1996 that could make things complicated, plus i dont think there is anything bad enough to be replaced

**Comment by Grangach** [comment]
I think having a mode that feels completely different than the normal game is good, I would be more excited about 64 physics than the models cause it would be a fun and different experience. It would probably be a little imbalanced because characters tools would be built around the engine but it sounds like a lot of fun. That being said it sounds like a shit load of work, and I wouldn't put it high on the priority list.

Would the 64 models be alt costumes, a wholesale mode, or both?

**Comment by PyotrLuzhin** [comment]
@DarkLink1996 That's a cool idea! As I write the code, I'll look into that. I don't know if it's possible though

**Comment by Nekudot** [comment]
If possible, keep the current menu and replace the broken tourney mode with N64 mode

**Comment by Kippy232** [comment]
@Nekudot I feel like that would be an overly complicated alternative to simply renaming a mode and changing what texture/model the files load. Though I do see your reasoning, to essentially rewrite an entire mode seems like a bit much.

**Comment by Nekudot** [comment]
I wasn't talking about rewriting a mode though, the PMDT used a code so that when you select Tourney the game sends you to Rotation. If menu editing is possible like DarkLink1996 was suggesting, then maybe the unused menu icon could be used to access Retro mode directly. This is a really minor thing that may not be worth the trouble.

**Comment by Kippy232** [comment]
@Nekudot I understand now. I suppose it would be something worth looking into in the future, for those who want both invisible mode and retro, separately. It may take some time to implement, if ever implemented at all, however. Good idea nonetheless

**Comment by DarkLink1996** [comment]
I meant more of how the PMDT had which Stamina type you would play with. In the Options/Rules menu, so that you can toggle "Retro Physics" on or off. Y'know, like this:
![smash](https://cloud.githubusercontent.com/assets/16201501/11980049/b3833d18-a94c-11e5-9068-963dee76547e.png)

**Comment by vinegar97** [comment]
@DarkLink1996 that's....actually a pretty good idea, i'm not sure how difficult it will be to implement, though.
 Edit: now that i think about it, your idea might not work if the button is going to be where it is in the mockup, because that will cause problems with stamina mode itself since it also uses that slot and the two modes can be mixed together.

**Comment by DarkLink1996** [comment]
Well, it doesn't have to be there. No one uses Damage Ratio, right?

**Comment by vinegar97** [comment]
I don't think so, no....then if it's possible I'd love to have the option available, and it being on by default.

**Comment by bb010g** [comment]
I could see Damage Ratio being missed. However, I don't know where else such a switch would go. It seems like a lot for just one option.

**Comment by papajefe** [comment]
Why not just change "Light" or "Heavy" Gravity to N64 Gravity code?

**Comment by ghost** [comment]
@bb010g 64 going indie probably means that this and similar issues should get closed.

**Comment by bb010g** [comment]
Maybe reopen when the N64 project gets closer, but not until then.

**Comment by fihn14** [comment]
why not just add the n64 costumes for the original characters and add a switch to turn on n64 physics
