### ISSUE TITLE
Roy new alternate costume missing eyes

### ISSUE THREAD

**Issue by Dockolm** [TheOriginalSINe/Project-M-CC#198]
![00000000-1](https://cloud.githubusercontent.com/assets/10415146/11851163/75d53d7e-a431-11e5-936d-25407d7e7537.png)
As you can see, his eyes are completely black. Tested on Dolphin. Normal costumes are alright.

**Comment by Hellraz0r** [comment]
Well, that's terrifying.

**Comment by Hex97** [comment]
Made an account just because of this one. I love the lack of eyes on this costume. It's like the greatest thing ever. I thought you guys did it on purpose but when I saw this I knew it was a bug. Please leave it if you can. Me and my friends love it. Great job btw, I really like what you guys are doing completing this where Project M left off. Can't wait to see it finished!

**Comment by jgd124** [comment]
Um, can we _not_ leave it in? This is a completion build after all.

**Comment by TheGessoman** [comment]
Reverting to a previous version of FitRoy06.pac/.pcs solved this for me. Hex97, if you want to keep it on future builds, backup your current FitRoy06.pac and .pcs (projectm/pf/fighter/roy) and then overwrite them in any new build.

**Comment by Hex97** [comment]
Thanks Gess!
I appreciate the info. Glad to know I'll be able to keep scary Roy. Keep up the good work guys!

**Comment by ghost** [comment]
https://cdn.discordapp.com/attachments/123214554363723782/127046902100393985/FitRoy06.pcs 
https://cdn.discordapp.com/attachments/123214554363723782/127046905883656192/FitRoy06.pac
 These should fix the Roy eye issue. This models eyes apparently work differently from all the others when it comes to the eye highlight texture.
