### ISSUE TITLE
Lyn: Counter Frame Timing

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#26]
Counter frame timing is currently not consistent with the rest of the cast. Current state: 9 startup frames, 6 active frames, and 72 cooldown frames. Total 87 frames. All other counters are exactly 60 frames. Roy: 7 startup, 4 active, 49 cooldown. Marth: 4 startup, 2 active, 54 cooldown. Ike: 5 startup, 6 active, 49 cooldown)

Suggested fix: To keep in line with PMDT design, reduce total duration to 60 seconds and change her startup and active frames to the average of the other three counters. 6 startup, 4 active, 50 cooldown.

**Comment by Hellraz0r** [comment]
Think we could change her dspecial from a counter to how it worked in the leaked video?

**Comment by ghost** [comment]
Not entirely sure if PMDT deliberately stepped away from that version of the move, or it was meant to be the same but just was broken in the leaked build.

If anyone good with PSA could look at the original leaked build move data and see if there are any hints about the moves intended function, that may help decide what to do with it.

**Comment by ghost** [comment]
According to the leaked video from a while back, it seemed to be a dash forward into a sword slice, similar to her down tilt. It seems that they changed it and made it into her side b though.

**Comment by JCOnyx** [comment]
No, her sideB, named mirror step, had an image that once leaked a long time ago.  Sadly I don't have the image I'm referring to, but mirror step could either let you dash through opponents and have the option of coming out facing either left or right to dodge and counter attack an opponents laggy move, or you could press back to perform a street fighter esque backdash with like 3 frames of intangibility.  From the looks of it in the leaked video, they never implemented the backdash, most likely because it would give the move a lot more utility then they wanted.

EDIT: Found the image
http://i.imgur.com/Wnbkriu.jpg

Vantage, or her downB, was a move that sent out a series of activation boxes in a direct line in front of her.  If the opponent came in contact with one of them she would lunge forward and slice through the opponent.  Based on the leaked video, it was weak the closer to the opponent you were and if you triggered it at max distance would put the opponent in sort of stunned state like ZSS.  Not sure how they did that, thought it was a ZSS exclusive thing, but that's how it is in the leaked video.

**Comment by ghost** [comment]
I guess I thought they remade it, since it looked like a similar animation. When i saw her down b in the video, i thought she did a sliding dash, but  your description matches the video more. If that could be implemented in, that would be great.

**Comment by ghost** [comment]
Like I said before though, that video is over a year old. The question is, did they deliberately scrap that move by the time of our current dev build, or was it meant to still work but was broken for some reason

**Comment by JCOnyx** [comment]
That I'm sure only the PMDT knows, and only the select few who were balancing her.

I've found someone who has reverted the ground version of Vantage back to what it was in the leaked video, but due to paranoia I won't link to it here.  He still needs to fix the aerial version, so it's a work in progress.

**Comment by Hellraz0r** [comment]
Regardless of the PMDT's intent with Lyn's down special (I seriously doubt they wanted just another counter, plus it's still called Vantage) the only definite implementation of the move we have is the one in the old video. I feel like making it something else is too much of a deviance.

**Comment by ghost** [comment]
This can be closed. The move has been changed to Vantage.
