### ISSUE TITLE
Retro Mode Costumes

### ISSUE THREAD

**Issue by Darquezze** [TheOriginalSINe/Project-M-CC#268]
Some of the costumes look mess up and there's no alternative color for any of the characters. Is this international?

**Comment by vinegar97** [comment]
Retro mode is still in a work in progress IIRC, and was included for bugtesting.

For characters that don't have alternate colors, that's because the original clear mode didn't look for alternate models for most characters, so they aren't being loaded, though @PyotrLuzhin has been working on a code for that.

**Comment by Darquezze** [comment]
@vinegar97  I was thinking it was in bug testing because come on, u can't make something fast like in 3 weeks and that's cool thats there's going to be more costumes but is there going to be alts? Like Dr.Mario,Mr.L, armored mewtwo and  etc.

**Comment by vinegar97** [comment]
Dr. Mario is being worked at over at discord,  other costumes might follow suit.

**Comment by jgd124** [comment]
@Darquezze 

To repeat, I also don't believe that you _can_ add more than the one costume currently.

The PMDT couldn't do it, I don't believe they planned on doing it. (Especially because they didn't have time.)

This issue should be closed as it's neither a bug nor an issue that could be conceivably worked on at the moment.

EDIT: I stand corrected.

**Comment by bb010g** [comment]
Leaving this open while we're waiting on @PyotrLuzhin about the costume code.

**Comment by andy-bond** [comment]
As discussed in the Discord chat, many people have expressed interest in adding a Fighting Polygon Team reskin as an alternate costume for Retro/N64 Mode when it is completed.

**Comment by ghost** [comment]
@bb010g this should get closed, 64 mode is indie. (yeah, there's quite a bit of clutter in these entries, sorry).
