### ISSUE TITLE
Knuckles' Victory and Side & Down Taunt Animations

### ISSUE THREAD

**Issue by MrGameCrazy** [TheOriginalSINe/Project-M-CC#294]
It seems that they have been reverted back to their dev build version (besides his up victory animation).

**Comment by Kippy232** [comment]
Can confirm. Side taunt uses the "Bring it on!" clip, but shows Sonic's Side taunt instead ("You're too slow!" Down taunt shows the correct animation, but uses no sound slip, or an empty one. I'd assume the former. Can't confirm Victory animation being Sonic's (because he just wont do it! T.T). If it is reused, however, then (recalling the previous awkwardness) it could be changed to Knuckles doing a back-flip, then striking either the same pose or one similarly appropriate.
