### ISSUE TITLE
CSS Arrangement

### ISSUE THREAD

**Issue by pharoahfawcett** [TheOriginalSINe/Project-M-CC#299]
really minor, but the "random" icon is in a rather random spot with the new arrangement

my suggestion would to swap "random"'s placement with game & watch, then move random to the far right. this would make the most sense if the original PMDT character order is being ignored (i.e swapping Wario and Mario)

**Comment by bb010g** [comment]
![New roster](https://cdn.discordapp.com/attachments/123214554363723782/135505761336819712/PMCC_Rosterc.png)

From Nekudot on the Discord. It's not perfect, but it's a start.

**Comment by AgentBlizz** [comment]
Can we switch G&W with Olimar, and ROB with ICs? I'd like to keep the 4 classic characters together, and the human-looking ICs with Pit
otherwise it looks pretty good theme-wise

**Comment by Kippy232** [comment]
I could care less where each individual fighter goes, but I feel like RANDOM should be centered. Of course for that the whole thing would have to shifted. I'll see if I can do something, but I guess that works

**Comment by Nekudot** [comment]
@AgentBlizz I did it like that because Game & Watch is mostly associated with Mario (G&W gallery) and Wario (WarioWare). The other three Retro characters are side by side there, with Pit next to Fire Emblem. I like it as is, but I see what you mean, if more people are okay with the change, I (or someone else) will change it.

Unfortunately, Random can't be centered in this layout.

**Comment by Shin-F** [comment]
Random looks awkward in the center, it should definitely stay on the end IMO.

**Comment by ghost** [comment]
I think we already discussed this in a different issue. #203

Some designs posted there

![image](https://cloud.githubusercontent.com/assets/7049878/12298908/6ef0c584-b9e2-11e5-94b0-97da49b20adf.png)

![image](https://cloud.githubusercontent.com/assets/7049878/12298917/7494492a-b9e2-11e5-8b94-90aeaec62a7c.png)

![image](https://cloud.githubusercontent.com/assets/7049878/12298946/97aff5da-b9e2-11e5-9625-1586a496b693.png)

**Comment by Nekudot** [comment]
Those CSS designs will require more edits, and they look ugly. It should be 10,10,10,10,6 or 8,10,10,10,8. The former is already done, we just need to choose the character placement. What was so wrong about the CSS I edited? The only thing I could see changed is swapping G&W with Olimar and changing the order of the Retro characters.

**Comment by ghost** [comment]
"Ugly" and what the layout design "should be" are completely subjective, just like many of the changes you made to character order.

There is no clear reason given for why reordering the characters in each franchise, or shuffling the franchises around is objectively better than the original layout. And if there is no clear reason to change something, don't. There will be as many people who dislike the changes as there are who like the change. Rather let the general design be as close to the current roster because that's the placement people are used to when selecting their characters.

Another reason, in keeping the project goal of following PMDT design, lets look at what they did for past releases.

![image](https://cloud.githubusercontent.com/assets/7049878/12301699/644cb522-b9ef-11e5-80da-f88f15999940.png)

![image](https://cloud.githubusercontent.com/assets/7049878/12301702/66b1a48a-b9ef-11e5-8590-13a414f27eb2.png)

![image](https://cloud.githubusercontent.com/assets/7049878/12301705/6b4677f0-b9ef-11e5-8893-5b89e7863229.png)

As you can see, each addition to the roster introduced only minimal changes to the layout, generally only what had to be done to keep franchises together and the layout appealing, and each franchise stayed in the same general area of the screen.

**Comment by Nekudot** [comment]
I don't really have to add "IMO" to every comment I make, right? I mean, isn't that a given? And the 9,10,10,9,8 looks bad and inconsistent with every CSS ever, sorry
Anyway, my CSS was based on the PMCC/leaked builds with a few changes, NOT the PM 3.6 Layout. The PMDT made some bad decisions with their layout because they were aiming for Melee 2.0 at the beggining, and they unfortunately stuck with it (why the hell are secondary characters the first in the row? What's up with the placement of the Retro characters?). The dev build CSS is a lot better, no need to go back.
IF your want to really make this PMDT 2.0 with every decision made by them, be it good or bad, why not shut down too? /not serious :P

Edited CSS (Dev Build Version) with AgentBlizz suggestions (No idea what to do with the pokemon order, so I put them in the good old "Playable in Smash" way
![pmcc rostera](https://cloud.githubusercontent.com/assets/16191641/12302532/405007f4-b9eb-11e5-8885-27f9963af3bd.png)

Edited CSS (PM3.6 Version)
![pmcc rosterb](https://cloud.githubusercontent.com/assets/16191641/12302574/65d61ab8-b9eb-11e5-8d1f-cb5a2624e1e2.png)

Which one looks better? Ignore the PMDT previous work and answer this honestly. We need more opinions here... Either way, the current CSS needs a replacement ASAP, even if it's not permanent.

**Comment by pharoahfawcett** [comment]
just wanted to pop in and say that the positioning choices of PM were most likely a psuedo-tribute to Melee where (most) clones were put towards the side and slightly offset. i say pseudo because characters like wario and ZSS aren't really clones, and Mewtwo came before Lucario (however you could argue that Lucario was first in Brawl). i think in PM, ganon is cleverly positioned next to falcon as it would be silly to separate him from the Zelda series with how large the roster is.

![gale01-59](https://cloud.githubusercontent.com/assets/16218324/12309856/c28bee16-ba01-11e5-8c5f-bd83a085c32c.png)

if you're going for accuracy, this is the CSS to use:
![tru roster](https://cloud.githubusercontent.com/assets/16218324/12310180/abf038e0-ba03-11e5-984a-a830e8fd9e1f.png)

basically it's just the one posted above, with Lyn set between Ike and Marth, so that Roy is given his outside offset. that would stay the truest to both Melee and Project M 3.6. 

also i just wanted to point out that i think a brilliant touch in is the positioning of Sami next to Snake, didn't know if it was intentional. initially i thought about moving them to the side, but I realized it would throw off the 1st party/2nd party/3rd party ordering

edit: additionally, noticed a few things and I made this CSS if you really wanted to fuck things up
![tru roster 2](https://cloud.githubusercontent.com/assets/16218324/12311128/fb296e58-ba09-11e5-89db-bf8421e6ed17.png)
- switching metroid/pokemon series sorts all by 1st/2nd/3rd party
- moving kid icarus past kirby + putting lyn to the left of Ike puts Lyn and Pit together (sort of referencing the fact that Lyn was cloned from Pit)
- incidentally, mewtwo and roy are now touching which is fitting in a way since they were the first PM characters

some people may be like "hey Pit isn't 2nd party" which was true at the time of Brawl, but considering he's primarily developed by SORA now i figured it wasn't too horrible

the only thing that still bothers me is ICs and ROB floating in the middle there, but between that and separating DK from the Mario series, I decided it was the lesser evil

**Comment by Nekudot** [comment]
You can also swap Isaac with G&W, and Pit with Olimar to have all the new characters touching the ones they were cloned from, but that would mean separating Isaac from Sami and changing Pit's position compared to PM3.6.
After the change, G&W (now at the bottom) would need to change places with ROB.

**Comment by Nekudot** [comment]
Oh, you edited it. (Can't edit on my phone)
My suggestions were for the first mockup

**Comment by Kippy232** [comment]
I'm more a fan of @pharoahfawcett's CSS. I feel like that fits the best. Just my two cents

**Comment by Nekudot** [comment]
Posting this here:
Barely edited PM3.6 CSS
![pmcc roster 361](https://cloud.githubusercontent.com/assets/16191641/12313907/9a578560-ba31-11e5-8a86-bdcda2fa4315.png)
Keep in mind that this is just a temporary solution to the broken CSS that is included in the main build now.
Unless someone sets up some kind of poll with as many choices as possible or someone decides to take charge and remove the "community" aspect of this project, this isn't getting anywhere anytime soon

**Comment by Kippy232** [comment]
@pharoahfawcett I feel like Olimar and Pit should be switched here:
![image](https://cloud.githubusercontent.com/assets/16312991/12313988/922dc22c-ba32-11e5-887a-a79664a0e25f.png)
Aren't Metroid and Kid Icarus under the development or concept of the same guy at Nintendo? I forget. It simply seems more fitting to me for the two series to appear next to each other.
Following that, we could shift the Kirby series next to the Mother series and stick Olimar between Ike and King DeDeDe

**Comment by bb010g** [comment]
Ok. To recap, we have two options:
- New style (dev build)
- Melee style (PM 3.6)

The most favored new style one seems to be:
![project recovery](https://cloud.githubusercontent.com/assets/16191641/12302532/405007f4-b9eb-11e5-8885-27f9963af3bd.png)

The benefits of this include going with what the PMDT seemed to be wanting to switch over to and cleaner arrangement of characters just by when and where they were released & significance in their franchise.

The most favored Melee style one seems to be:
![maylay](https://cloud.githubusercontent.com/assets/16191641/12313907/9a578560-ba31-11e5-8a86-bdcda2fa4315.png)

The benefits of this include easy transition from 3.6 or 3.61 and keeping with the Melee feel.

Which do we want to go with? [Strawpoll because why not.](http://strawpoll.me/6531374)

**Comment by pharoahfawcett** [comment]
i actually didn't realize dev build had reorganized rather than just reshaped into a rectangle, dev order should be the one you go with without a doubt.

![final one](https://cloud.githubusercontent.com/assets/16218324/12315256/ba64fd3c-ba2d-11e5-8813-a4176204b444.png)

the dev one you linked wasn't actually in the order of the dev build so i fixed it (lucario/mewtwo positioning and lyn positioning, rob switched with g&w to match with previous CSS's). obviously there's freedoms taken with the one-off retros but it's just about the only good way to organize them if we're going by 10s.

**Comment by AgentBlizz** [comment]
Since people are throwing designs on here left and right, I thought I'd try my hand at the new 10-10-10-10-6 layout. The first one (by Azer-X) is the one I think we should use for the 1.0 release, and the other is the one I think we should use for the one with Sami and Isaac on the CSS. Both are inspired by PM 3.6, and keep the characters in familiar locations as well as group series together.
![css_v1](https://cloud.githubusercontent.com/assets/16184847/12316788/48f6c374-ba50-11e5-98e2-bfa1be96bcfd.png)
![css_v2](https://cloud.githubusercontent.com/assets/16184847/12316790/4d1f46b0-ba50-11e5-895b-3178414c3969.jpg)

**Comment by JackpotSHUnited** [comment]
Having Wario in the top left corner just looks weird in my opinion. The only reason he was ever there in previous builds was "because Melee" which isn't a valid reason for anything. I think we should go with the dev build style just because it looks the most "normal" and they were going to switch to that style anyway.

**Comment by pharoahfawcett** [comment]
yeah, the only reason i had made my original CSS with the "melee" style was because I didn't notice the CSS had been rearranged for the dev build. see the last one I suggested for the one that stays closest to the devbuild

**Comment by Nekudot** [comment]
In the AgentBlizz image, I don't like splitting characters from the same series in 2 different rows, like he did with the Metroid series. Otherwise, it's fine.

And what's the reasonong behind that pokemon order in the leajed build? The FE series is organized by their debut in Smash, shouldn't pokemon be the same? A part of me wants to organize them by pokedex number, but that would leave Pikachu in the middle...

**Comment by pharoahfawcett** [comment]
you either go by dev intent or by how you personally want to arrange a CSS. the project is about dev intent. we could argue for days about who needs to go where, but the best answer is to go with the leaked arrangement with the most minimal edits.

**Comment by pharoahfawcett** [comment]
Nano said he had no complaints w/ [this one](https://cloud.githubusercontent.com/assets/16218324/12315256/ba64fd3c-ba2d-11e5-8813-a4176204b444.png) so i'll drop the modified files Monday unless anybody would like to do them before I'm able to get to my desktop

**Comment by Nekudot** [comment]
Looks like the Dev style one is the winner to me. Anyway, here's the code needed:

In the current GCT, replace:

\* 00090d0c 0515011a
* 0a071325 1002240e
* 0f140616 1f172903
* 04182208 23202e2b
* 2c2a0b19 112d212f
* 12262730 32310000

With:

\* 00090d0c 0515011a
* 180a0713 25030402
* 240e0f14 0823202e
* 2b2c2a06 161f0b19
* 112d212f 17102212
* 32312627 30290000
For the New style (dev build) CSS

Or:

\* 1500090d 0c05011a
* 320a2507 1310120e
* 0f022414 2e200823
* 2b2c2a17 0304190b
* 1806161f 212f112d
* 22312627 30290000
For the Melee style (PM 3.6) CSS (not tested)

The CSS code is bigger, but those are the only relevant lines here

If someone wants to make their own personal CSS:
2 digits in the code above represent a character and their position in the CSS, so 00090d0c make the character order in the CSS Mario, Luigi, Peach, Bowser. You can swap characers based on this or reorder them completely.
If you rewrite it from scratch, remember to use all 46 slots. The code needs to be 6 lines long and end with 0000. If yours isn't like that, you forgot to add one or more characters to the code.
Here's a list of the IDs for the characters in PM:
https://www.dropbox.com/s/h8la72xbkwlxpn7/CSS.txt?dl=0

**Comment by bb010g** [comment]
@Nekudot Could you PR the dev style?

**Comment by ghost** [comment]
Still going to go with the placement is completely subjective and everyone will have their own preferred way of doing it. Therefor, we should change it as little as possible from 3.6 because any change just messes with people who are used to their characters in certain spots, and there is a 0% chance of any new arrangement being agreed upon by any kind of majority.

**Comment by Hex97** [comment]
Honestly, I don't see what the big deal is here guys. All I would want is the Random option to be in the center. Just speaking as a simple player: I really doubt people would mind that much to whatever the placement was as long as it didn't look weird and I don't me how the franchises are ordered I mean the overall shape of it. The only real problem I see is that the Random option is in an odd spot, thus throwing off the whole thing. Any of the options presented thus far would be more than adequate to please the average player ( I literally couldn't tell the difference between a lot of them).

**Comment by bb010g** [comment]
@Azer-X The thing is that the PMDT were going for a new layout, so why not use that? Completing their vision is what this project's all about, and this is a change we're pretty sure about.

**Comment by Nekudot** [comment]
@bb010g I literally can't do a PR until I have access to my PC and broadband internet, which won't be until Jan 25 at the earliest. Anyway that code is easy to replace using a Hex editor, so anyone can do it.

@Azer-X I agree, but your logic can be applied to the Dev build version too, as thats what everyone who downloaded PMCC has been using. That's why some kind of poll was needed. I'm fine with either one, but I'm using the New style one because I don't like Wario's and Wolf's placement.

@Hex97 Random can't go in the center in this layout, and any change to it would require someone who's used to menu editing. Random in the corner is something you get used to, ever since Brawl that has been its placement in all the games. Hiding the random tile and leaving the CSS as a 9x5 rectangle was something I wanted to do before though

**Comment by Hex97** [comment]
If centering it is not possible then putting it in the corner is 100% alright, and yea it has been like that for the games I just thought it looked really nice when it was centered.

**Comment by Tac24** [comment]
ha I'm willing to bet the original devs would have had to at some point would have to bring this topic up since in intro of 4 characters changes the CSS quite a bit.

I love what and how they did with mewtwo and roy... why not keep as close as 3.6? people are used to where there characters are... why change it so much?

**Comment by bb010g** [comment]
@Tac24 Dev build style CSS is the CSS the PMDT would have used going forward. We're trying to stay as close to what they planned as possible.

**Comment by LnktheWolf** [comment]
What's the thought on moving to that css picture that was supposedly of 4.0? (The one with all the marios)
