### ISSUE TITLE
Jigglypuff uses Brawl BPs

### ISSUE THREAD

**Issue by pharoahfawcett** [TheOriginalSINe/Project-M-CC#301]
title

**Comment by Jigglypoof21** [comment]
I made some if you want
![infface 361](https://cloud.githubusercontent.com/assets/16619835/12214681/6ff551d0-b653-11e5-9a63-4ddf8caf5052.png)
![infface 362](https://cloud.githubusercontent.com/assets/16619835/12214685/73da170e-b653-11e5-9ecf-34f383901194.png)
![infface 363](https://cloud.githubusercontent.com/assets/16619835/12214686/7719f72c-b653-11e5-973e-03de8e62beb4.png)
![infface 364](https://cloud.githubusercontent.com/assets/16619835/12214687/7bf8e758-b653-11e5-801d-c06b56784d95.png)
![infface 365](https://cloud.githubusercontent.com/assets/16619835/12214688/8184df2e-b653-11e5-9050-0a46e8d45343.png)
![infface 366](https://cloud.githubusercontent.com/assets/16619835/12214689/8553e73a-b653-11e5-8f9c-c46aebcd710f.png)
![infface 367](https://cloud.githubusercontent.com/assets/16619835/12214690/89dbd128-b653-11e5-86d4-a1c0e86b87aa.png)
![infface 368](https://cloud.githubusercontent.com/assets/16619835/12214691/8f12bbd4-b653-11e5-915c-7ea9df29bd9f.png)

I just made them from cropping and re-sizing the existing CSPs

**Comment by PKSmashOmega** [comment]
Jigglypuff's Bps are fine for me. But Wario, Mewtwo, Ivysaur and Charizard still need new BPs.

**Comment by Jigglypoof21** [comment]
The Brawl costumes use the new artwork.  The PM costumes (crown, fairy wings, and headband) use Brawl-styled BPs.  Those costumes are InfFace366-368.

**Comment by Tac24** [comment]
puff isn't the only character/ other characters with color swaps have the brawl/3.6PM BP

even saw this on final boss stream haha. so PM:CC is a thing being played and talked about for sure

**Comment by bb010g** [comment]
Final Boss just used the leaked CSPs, not 3.61.

**Comment by Tac24** [comment]
I know, it's a sign of awareness from the community though

**Comment by Jigglypoof21** [comment]
You can use these for Charizard (InfFace 281-288). 
![infface 281](https://cloud.githubusercontent.com/assets/16619835/12252211/242a8d04-b88a-11e5-8d05-4eaf85af4308.png)
![infface 282](https://cloud.githubusercontent.com/assets/16619835/12252213/27d9bf92-b88a-11e5-995b-8f7e84523db0.png)
![infface 283](https://cloud.githubusercontent.com/assets/16619835/12252218/2f054912-b88a-11e5-8b49-7dd2074215f7.png)
![infface 284](https://cloud.githubusercontent.com/assets/16619835/12252240/54ee3558-b88a-11e5-8ab7-59667beb33a6.png)
![infface 285](https://cloud.githubusercontent.com/assets/16619835/12252225/3715fdcc-b88a-11e5-9490-16b5b8c3960f.png)
![infface 286](https://cloud.githubusercontent.com/assets/16619835/12252226/37176f36-b88a-11e5-8c0f-269ae07b933e.png)
![infface 287](https://cloud.githubusercontent.com/assets/16619835/12252227/3717dbb0-b88a-11e5-82ed-b45941cf60ef.png)
![infface 288](https://cloud.githubusercontent.com/assets/16619835/12252228/3719ccfe-b88a-11e5-9851-4ec87d383e29.png)

They don't look the best because they come from the CSPs which are in CMPR format. The armored Charizards actually have matching BPs already (InfFace 287/288).

**Comment by ghost** [comment]
@bb010g perhaps this should get closed, since we plan to replace the leaked CSPs for consistency across the board.
