### ISSUE TITLE
Knuckles shares animations with Sonic

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#338]
Just like the issue that @RikiDVX posted about Isaac, Knuckles shares most of his auxillary animations with his base character, Sonic.

**Comment by cimpyhigh** [comment]
I think this is fine, considering Knuckles and Sonic often act similarly in their games. Isaac and Ike are two very different characters, but knuckles and Sonic are from the same universe. Although, it'd be interesting to see how the animations would differ...

**Comment by bringobrongo** [comment]
I believe he means stuff like taunts and victory animations.

**Comment by RikiDVX** [comment]
Auxillary animations (or at least how I used the term) are animations like the walk cycle, special fall, taunts, wins, airdodge, rolls, etc.

**Comment by LnktheWolf** [comment]
I think that some should stay and some should change. The ones that make sense should stay, but if it doesn't make sense for it to be the same to draw a parallel, then it should be changed.

**Comment by vinegar97** [comment]
we should make a list of animation that need to be replaced, and whether the one we have now are placeholders, leftovers from sonic, or generally need updating.

**Comment by Blackhawk789** [comment]
I agree that it would be worthwhile to look into what additional animations might help Knuckles to be more unique from Sonic. I immediately noticed and appreciated Knuckles' animations that were a callback to the Genesis era (i.e. his laugh taunt, edge teeter, and glide turn). Based on that trend, I might start by recommending his falling sprites from Sonic and Knuckles.

![knucklesfallanimation](https://cloud.githubusercontent.com/assets/17266971/13070295/4eabd2c8-d440-11e5-952b-396a5aa0e3c7.png)

![knucklesfallanimation2](https://cloud.githubusercontent.com/assets/17266971/13070336/99b2f8d2-d440-11e5-9bd4-51ee61bbbd75.png)

I believe the first pose would be a cool and fitting choice for either his falling or special fall animation, while the second pose is at least a canon possibility for his special fall.

**Comment by vinegar97** [comment]
let's make a comprehensive list first, then we can start discussing each animation one at a time.

**Comment by EdinmavarThe3rd** [comment]
I feel Iike this should be closed he has almost all of his animations done and like cimpyhigh said he's in the sonic universe si some animations would be the same

**Comment by robosteven** [comment]
EdinmavarThe3rd, it's still a good idea to compile a list for the sake of organization. His getup attacks and ledge options should look a little more like Knuckles instead of spinning really fast and kicking like Sonic. They're basically passable as they are though, hence the Low-Priority. It just comes down to be a quality thing, it looks better when they're different I guess.

Anyway, here's a list of what I have so far.

Identical moves:
Getup Attack on back
Getup Attack on front
Ledge Roll at <100%
Ledge Attack at <100%
Ledge Normal Getup at <100%
Ledge Roll at >100%
Ledge Attack at >100%
Ledge Normal Getup at >100%

The only ones I would change are the on-ground getup attacks, they feel very Sonic. I think Knuckles's Ledge Attack at >100% should be a punch or something instead of the kicks just for reason of it feeling uncharacteristic, at least in the animation somehow.

**Comment by ghost** [comment]
This animation diversification is a work in progress, but know that work has been started. In particular, all Guard animations, fall, and up special have had their animations changed, if not a few  more as well.
