### ISSUE TITLE
turbo item update?

### ISSUE THREAD

**Issue by LinkTahuterasuSpirit** [TheOriginalSINe/Project-M-CC#383]
now i'm sure we all know that pmdt planed on changing the way the turbo item looked on the field i believe they talked about making it an energy drink, are you guys planing on doing that or not or did you guys already do it?

**Comment by bb010g** [comment]
No, we all don't know. Please source this.

**Comment by ghost** [comment]
As far as I know, nothing has been said about it. But, the problem is that the eating animation plays since it's over curry. Not sure if fixing that would be possible, and if it's not, I am for using an energy drink icon for it, due to it looking odd when you eat the icon. PurpaSquirt made an energy drink one though, and I believe it's finished.

**Comment by PhoxFyre** [comment]
in cas if your wondering i have the item that was specified
It was made by and mentioned by purpasquirt

_bb010g: Please use the edit button._

**Comment by kalebsanders007** [comment]
It was made by and mentioned by purpasquirt

**Comment by LinkTahuterasuSpirit** [comment]
@RadiantThunder4 @kalebsanders007 ah i knew i've seem the item icon somewhere i just didn't who made it

@bb010g i though i read this on something posted by pmdt i don't remember where i saw it

**Comment by bb010g** [comment]
Closing until a reliable source is provided.
