### ISSUE TITLE
This build's test Results. (The Info you need before you setup PM EX

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#427]
Mewtwo and Roy can't pair up with Kirby on any stage.
It crashes the game everytime we do so.

I tested this Sami Build with a new idle pose, and it worked!
https://github.com/Project-M-CC/Project-M-CC/pull/334

Surprisingly, it didn't crash the game at all. It nerfed and gave sami a few new moves that i think you should both try out, and edit yourselves.

Knux and Sami Paired with kirby is Unstable.
When inhaled and swallowed, kirby freezes in place.
The only way to unfreeze him is to... of course...  punch him.

Giga Bowser is known as Sami. That needs to be patched.

When on the character select screen, when you pair up "Random" with any other Character, it freezes both before, and after you go to the stage select screen.

Lyn, Issac, and Knux need new victory animations, final smashes, and clapping animations.

Knuckles snores and screams too loud.  Needs fixing.

Knuckles, Lyn and Issac also need to have new animations for when they run to a wall, or Roll, Taunt, Air Dodge, Sleep, and other "Useless" & "Obscured" animations.

**Comment by ghost** [comment]
This is all the info you guys need, before you prepare to swap to PM EX.

**Comment by ithunderHD** [comment]
Thanx for the info

**Comment by KorytheMaril** [comment]
When switching over to PMEX, a lot of these issues will automatically be fixed due to the nature of PMEX. Knuckles and Lyn are stated to have Kirby hats in the next update, but with PMEX, the Kirby glitches do not occur regardless due to the option to simply turn off the Kirby hat in the fighter.dat file. The Giga Bowser issue should also be resolved as a result of the nature of PMEX.

Knuckles seems to be the most complete: his clapping animation seems fine, but his victory animations could use a little work. Beyond that, the only other issue I've noted with Knuckles is one of his victory lines looping.

**Comment by ghost** [comment]
I remade this issue.

Close this one and respond to the other one.
https://github.com/Project-M-CC/Project-M-CC/issues/428

**Comment by TheSmashBoy** [comment]
Those issues were a pain in the clone engine but not in the PMEX engine. So this shouldn't be a biggie. But thanks for the info, though.
