### ISSUE TITLE
Any News? Updates? ANYTHING?

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#429]
Can you tell me what's going on now?
We need another update to the game. You guys need to update more characters in the build.

People are getting tired of waiting. I know it takes time, but... seriously. When will this ever update?
Sami's Moveset? Knuckles Moveset? Issac's Moveset? Lyn's Moveset? 

The Main Menu itself? A character patch? Something, please.

**Comment by TheSmashBoy** [comment]
Since you acknowledged how it takes time. Let me take it a step further on not only the time investment but the numbers needed to decrease the need for that work. 

 First, we were able to get two volunteers to animate Lyn, however only one is getting ahead (yet still stressed because of how much polishing and quality is needed given the parameters stated [see Manly's suggestions]), the other is still getting the hang of working Maya. That and combine the inevitable factors of RL that impede the speed of the progress. Practically speaking, we only have ONE working animator on Lyn. How bad is that? Well look at it this way: there is another working on her (E.g: Murphee Francis). But that guy is not narrowed on Lyn but focuses on other characters. It gets worst because he has gone ahead of updates for her and is unwilling to give insights and details. Another case: Riki. He is working on Isaac but Isaac is the only of the fours whose PSA were made on BBox 0.68b. That program is not only glitchy is super bad it crashes occasionally and adding frustration that it is hard to save changes. Knuckles; Silent Doom. Like MF; he is unwilling to help out PMCC and won't give details on his updates to AT LEAST, leave it up to us to employ it ourselves. Sami, sadly, has had no volunteers on our end. 

 We are at an innovative disadvantage because of: 1) RL factors on our volunteers. 2) Programs that crash and delay useful updates. 3) People out there unsympathetic [and to a certain extent, selfish] to help out our current cause (completing the F4's) so that our pro-leaks fan who have no idea what is behind the scenes, can be happy these fours AT LEAST, made progress. 

 Menu updates and other stuff like that are secondary, not in scope yet.

 I am not trying to 'put you down' or anything. Just trying to let you know that, if those people are tired of waiting, they have but two choices: 1) Get their asses involved in the program and start helping out, learn how to use Maya/3DS Max and work on the characters. 2) Leave and they can forget PMCC. It's really how that comes down to. In conclusion: we are on it but are small in numbers. Want some fast progress? Recruit animators and PSA'ers, good ones. Enough to get the job done. 5-10 animators can get Lyn done, in a matter of months (less is they are professionals). We don't need texture experts or stage modellers (at least not yet). We need animators, character modellers and PSA'ers. We have a few but just a few and they are probably 1st year college students or even 9th graders. So please understand our situation. If they want the fours to be complete, they can always lend a hand. Idling eternally isn't gonna get them completed anymore than complaining we are taking the leaks and 'slapping PMDT in the face' (as some would say) or taking too long to get a single update patched. We had a few commers who are hardly animators but they at least know the stakes, so if you are an animator or a PSA'er; get in the fray. If not, then it's irrelevant. 

 Sorry for this long post. Whoever asked you or if it was on your own, now you know. Peace.

**Comment by bb010g** [comment]
Closing, as the poster deleted their account and can't respond. (Please don't immediately delete after you post. It makes actual discussion extremely hard.)
