### ISSUE TITLE
How do I get Smash_Boy's dev build here?

### ISSUE THREAD

**Issue by TMG-FANFARE** [TheOriginalSINe/Project-M-CC#430]
All right, I've joined Riot and I was looking for the latest update. But I couldn't find one. After reading some old text, I found out that Smash_Boy has been making a build and has done some progress. I'd like to get his build, but 1. I can't talk on Riot because I haven't informed this staff that I joined, and 2. I don't know how to actually download (In other words, How do you do it with BrawlEX?). Can any of you guys help?

P.S. I'd love to help with this project, but I'm pretty busy. Is using Maya or PSA that difficult?

**Comment by TheSmashBoy** [comment]
@TMG-FANFARE The build you must be referring to is LXP CC. That's on Reddit in SSBPMCE. It's a partial build. So you need a pre-downloaded LXP build before you can even use it. LXP uses BrawlEx by the way, so your next move should be how to use it. Go here: https://smashboards.com/threads/updated-5-22-project-m-brawlex-a-starters-guide.430430/

 As for Riot. bb010g is the boss and moderator, you need to PM him on Riot to endorse you and give you a voice on the main thread. 

 P.S: Maya is a professional animators' program so there will be relative difficulties (unless you know a lot about animation and modeling). Same with 3DS Max. As for PSA, it's pretty difficult seeing as it is a recent program and not everything is 100% deciphered although enough is to make sufficiently stable PSA's. It depends which area you are more skilled with: PSA coding or animation/modeling. We particularly need animators. Since it's the big step to completion. After that comes the PSA's.

**Comment by TMG-FANFARE** [comment]
Ah that's unfortunate. The best I can do is cheer you guys on and look for good animators. Wish you luck!
