### ISSUE TITLE
Lyn: Facial Expressions

### ISSUE THREAD

**Issue by ghost** [TheOriginalSINe/Project-M-CC#54]
She lacks expressions for half-blink, blink, hurt, and talking. I made a version of her model with these, but the talking expression is...rough to say the least.

**Comment by Jeelix** [comment]
Here is some more information about this issue:

Someone with the name Large Leader found that the alt models for Lyn actually have facial expressions, but the default model doesn't. Someone else named ZX_BraveSol_ZX then applied the facial expressions to the default model. Here's the [forum post](http://forums.kc-mm.com/index.php?topic=75455.msg1349920#msg1349920).

I suspect the alt models were actually later versions of the model, but the older, default model was still used because the newer ones would crash the game.

**Comment by ghost** [comment]
EDIT: BraveSol's fix made new expressions for the default head. Nice.

The problem with using the alt models is that their heads are just the Assist trophy head, which is rather low quality in comparison to the rest of the updated Lyn model.

**Comment by JCOnyx** [comment]
I also encountered an animation problem when using ZX_BraveSol_ZX's models.  When performing the second part of her UpTilt, her eyes just sorta... freak out to say the least.  Like her cheeks warped up all the way to her eyebrows, it was sorta disturbing lol.

I do think we need to find a way to implement the expressions though.  It's a first step but not one I'd include in this build.

**Comment by ghost** [comment]
Srt0 animations would be the way to do it. I have no skill with that, however.

**Comment by ghost** [comment]
Lyn's expressions were added, so i'm closing this. A separate issue has been made for issues with visibility for them.
